version: '3.8'

services:
  db:
    image: mongo:3.6.4
    volumes:
      - mongo-data:/data/db

  web:
    build: ./web
    volumes:
      - ./web:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  mongo-data: